service: Booki-system-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  handler:
    handler: src/handlers.handler
    events:
# Handle Server
      - http:
          path: /
          method: get
          cors: true

      - http:
          path: /connectDatabase
          method: get
          cors: true
# Authentication User
      - http:
          path: /api/register
          method: post
          cors: true

      - http:
          path: /api/login
          method: post
          cors: true
# User Profile
      - http:
          path: /api/getuser
          method: get
          cors: true

plugins:
  - serverless-plugin-typescript