// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddMark: typeof import('./src/components/Icons/AddMark.vue')['default']
    Book: typeof import('./src/components/Icons/Book.vue')['default']
    DoneMark: typeof import('./src/components/Icons/DoneMark.vue')['default']
    HomeBody: typeof import('./src/components/Templates/HomeBody.vue')['default']
    Menu: typeof import('./src/components/Icons/Menu.vue')['default']
    NavBar: typeof import('./src/components/Templates/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
